# datasource
spring:
  datasource:
    url: jdbc:mysql:///springboot?serverTimezone=UTC
    username:  root
    password:  dingjie0822
    driver-class-name:  com.mysql.cj.jdbc.Driver

  # redis
  redis:
    host: 127.0.0.1 # redis主机ip
    port: 6379

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #mapper映射文件路径
  type-aliases-package: com.itheima.plugins_test.domain

